apiVersion: apps/v1
kind: Deployment
metadata:
  name: wintercode-website
  labels:
    app: wintercode-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wintercode-website
  template:
    metadata:
      labels:
        app: wintercode-website
    spec:
      containers:
        - name: wintercode
          image: wintercodenkjj/wintercode-website:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                    name: wintercode-secrets
                    key: NEXT_PUBLIC_API_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: wintercode-website-service
spec:
  selector:
    app: wintercode-website
  ports:
    - protocol: TCP
      port: 82
      targetPort: 3000
  type: LoadBalancer # Or NodePort if you prefer
